version: "3"

services:
  app:
    image: webdevops/php-apache:7.2
    ports:
      - "10080:80"
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /srv/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "UTC"
    working_dir: /srv
    volumes:
      - .:/srv

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "10081:3306"
